app/src/home/home.resolver.ts, app/src/total/total.resolver.ts
=> fix: :bug: id값 다르게 설정

app/src/home/home.resolver.ts, app/src/personalGeneral/personal.general.service.ts, app/src/total/total.resolver.ts
- 부족한 개수를 채울 겸 생각나는 특이한 사항들을 임시 데이터에 추가했습니다.
- gif 프로필 이미지인 경우
- 인트라 닉네임이 가장 긴 경우
- 아주 긴 칭호
- 평가 포인트 값이 음수
=> feat: :sparkles: add more mock data

app/pnpm-lock.yaml, app/src/common/models/common.coalition.model.ts, app/src/personalGeneral/models/personal.general.userProfile.model.ts, app/src/personalGeneral/personal.general.service.ts, app/src/schema.gql
간단한 버그 수정 입니다.
grade가 기존에 nullable로 설정된 이유를 모르겠네요...
- close #21
=> fix: :bug: UserProfile에서 누락된 데이터 추가, grade 타입을 non-null로 수정

app/src/common/db/common.db.aggregation.ts, app/src/home/home.service.ts, app/src/personalEval/personal.eval.resolver.ts, app/src/personalEval/personal.eval.service.ts, app/src/personalGeneral/personal.general.service.ts, app/src/scaleTeams/db/scaleTeams.database.schema.ts, app/src/scaleTeams/scaleTeams.module.ts, app/src/scaleTeams/scaleTeams.service.ts, app/src/total/total.service.ts, app/src/util/time.ts
evalInfo에 관련된 부분은,  추후 분리가 되면서 수정을 많이 해야할 것 같네요.
다음 작업에 변경된 내용 반영하면서 진행하도록 하겠습니다.
- close #31
=> refactor: :recycle: mongoose aggregation 도입, 성능 최적화

.github/workflows/cicd.yml, Dockerfile, app/src/app.module.ts, docker-compose.yml, entry.sh
=> feat: :sparkles: 배포 설정 및 자동화

.github/workflows/cicd.yml, Dockerfile, app/src/app.module.ts, docker-compose.yml, entry.sh
submodule 관련 브랜치 정리 후 다시 풀리퀘 올립니다
=> feat: ✨ githubaction

app/src/app.module.ts
=> fix: :bug: db connection string local 용 으로 수정

app/package.json, app/pnpm-lock.yaml, app/src/common/db/common.db.aggregation.ts, app/src/common/models/common.coalition.model.ts, app/src/main.ts, app/src/personalGeneral/models/personal.general.userProfile.model.ts, app/src/personalGeneral/personal.general.service.ts, app/src/scaleTeams/scaleTeams.service.ts, app/src/schema.gql, app/src/score/db/score.database.aggregate.ts, app/src/score/db/score.database.schema.ts, app/src/score/score.module.ts, app/src/score/score.service.ts, app/src/total/models/total.model.ts, app/src/total/total.module.ts, app/src/total/total.resolver.ts, app/src/total/total.service.ts
score module 추가했습니다.
개인 별 스코어 랭킹 정보는 coalitionsUsers 쪽에서 구현하는게 맞을 것 같아, score module 에선 제외하였습니다.
- close #36
=> feat: ✨  score

app/src/app.module.ts, app/src/scaleTeams/scaleTeams.service.ts
=> refactor: :recycle: docdb 호환성 및 env업데이트

app/src/scaleTeams/scaleTeams.service.ts
지난번에 document db 호환성 처리 작업하다 놓친 부분이 있었네요.
- close #50
=> hotfix: :bug: review 길이 구하는 부분 aggregation 수정

app/src/scaleTeams/scaleTeams.service.ts
지난번에 document db 호환성 처리 작업하다 놓친 부분이 있었네요.
- #50
=> fix: :bug: review 길이 구하는 부분 aggregation 수정

app/src/scaleTeams/scaleTeams.service.ts, app/src/score/score.service.ts
=> fix: :bug: $first 연산자 교체

app/src/app.module.ts, app/src/scaleTeams/scaleTeams.service.ts, app/src/score/score.service.ts
mongodb 6.0 버전을 사용하기로 하면서, 그에 맞게 다시 수정했습니다.
- close #60
=> refactor: ♻️  mongodb 6 0

app/src/evalLogs/evalLogs.service.ts, app/src/project/project.service.ts, app/src/scaleTeams/scaleTeams.service.ts, app/src/score/score.service.ts, app/src/total/total.service.ts
수정 사항들이 적고 오프라인에 모여있어 그냥 풀리퀘 하나에 뭉쳤습니다.
- close #64 
- close #65
=> refactor: ♻️  scaleteam score project

app/package.json, app/pnpm-lock.yaml, app/src/app.module.ts, app/src/schema.gql, docker-compose.yml, redis/Dockerfile, redis/entry.sh, redis/redis.conf
npm package 와 redis docker 설정만 추가했습니다.
어차피 local 네트워크에서만 연결을 받을 생각이라 bind address 를 * 로 했는데,
이 부분을 나중에 바꿔야할 수 있겠네요.
nestjs 에서도 env 사용 없이 일단 redis://redis:6379 형태로 사용 중 입니다.
- #68
=> feat: :sparkles: redis, cron 추가

app/src/app.module.ts, app/src/main.ts
임시 db 에서 서비스에서 사용할 실제 db 로 수정합니다.
=> chore: :bricks: 실 사용 db 로 수정, port 80 으로 수정

app/src/exam/db/exam.database.schema.ts, app/src/exam/exam.module.ts, app/src/exam/exam.service.ts
일단 당장 필요한 exam find 하는 기능을 추가했고, lambda 에도 이를 계속 반영해올 수 있도록 했습니다.
- close #81
=> feat: :sparkles: exam api

docker-compose.yml
=> chore: :bricks: docker port 변경, env 변경

app/src/cursusUser/cursusUser.service.ts, app/src/home/home.resolver.ts, app/src/home/home.service.ts, app/src/questsUser/questsUser.service.ts, app/src/schema.gql, app/src/total/total.resolver.ts, app/src/total/total.service.ts, app/src/util/time.ts
=> fix: :bug: 레벨 정렬 반대로, 블랙홀 카운트 월별로, 서클통과기간 합산으로 변경

app/src/cursusUser/cursusUser.resolver.ts, app/src/cursusUser/cursusUser.service.ts, app/src/cursusUser/models/cursusUser.model.ts, app/src/personalGeneral/models/personal.general.userProfile.model.ts, app/src/personalGeneral/personal.general.resolver.ts, app/src/schema.gql, app/src/total/total.resolver.ts, app/src/total/total.service.ts, app/src/util/time.ts
=> refactor: ♻️ cursus_user 에서의 프론트 요청 사항

app/src/api/coalitionsUser/coalitionsUser.service.ts, app/src/api/cursusUser/cursusUser.service.ts, app/src/dateRange/dateRange.service.ts, app/src/page/home/home.service.ts, app/src/page/personalGeneral/personal.general.resolver.ts, app/src/page/personalGeneral/personal.general.service.ts, app/src/util/time.ts
=> style 🎨  naming

app/src/api/location/location.service.ts, app/src/page/home/home.service.ts, app/src/page/personalGeneral/personal.general.service.ts, app/src/util/time.ts
=> refactor ♻️  use date range

app/src/api/coalitionsUser/coalitionsUser.service.ts, app/src/api/cursusUser/cursusUser.service.ts, app/src/api/location/location.service.ts, app/src/dateRange/dateRange.service.ts, app/src/page/home/coalition/home.coalition.service.ts, app/src/page/home/user/home.user.service.ts, app/src/page/personal/general/personal.general.service.ts, app/src/statDate/StatDate.ts, app/src/util/index.ts
Date 를 상속받게하여, Date 와 호환이 되면서도 각종 Date 연산을 편하게 할 수 있도록 했습니다.
- close #125
=> refactor: :recycle: Object Time => Class StatDate

app/src/api/cursusUser/cursusUser.service.ts, app/src/api/questsUser/questsUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/page/home/coalition/home.coalition.resolver.ts, app/src/page/home/coalition/home.coalition.service.ts, app/src/page/home/coalition/models/home.coalition.model.ts, app/src/page/home/eval/home.eval.resolver.ts, app/src/page/home/team/home.team.service.ts, app/src/page/home/team/models/home.team.model.ts, app/src/page/home/user/home.user.resolver.ts, app/src/page/home/user/home.user.service.ts, app/src/page/home/user/models/home.user.model.ts, app/src/page/leaderboard/eval/leaderboard.eval.resolver.ts, app/src/page/leaderboard/eval/leaderboard.eval.service.ts, app/src/page/leaderboard/exp/leaderboard.exp.resolver.ts, app/src/page/leaderboard/exp/leaderboard.exp.service.ts, app/src/page/leaderboard/level/leaderboard.level.resovler.ts, app/src/page/leaderboard/level/leaderboard.level.service.ts, app/src/page/leaderboard/models/leaderboard.model.ts, app/src/page/leaderboard/score/leaderboard.score.resolver.ts, app/src/page/leaderboard/score/leaderboard.score.service.ts, app/src/page/leaderboard/util/leaderboard.util.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/models/personal.general.userProfile.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/projectInfo/models/projectInfo.model.ts, app/src/page/projectInfo/projectInfo.resolver.ts, app/src/schema.gql
=> style 🎨  naming convention

app/src/api/cursusUser/cursusUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/common/db/common.db.query.ts, app/src/page/evalLog/dto/evalLog.dto.getEvalLog.ts, app/src/page/evalLog/evalLog.module.ts, app/src/page/evalLog/evalLog.service.ts, app/src/page/personal/eval/models/personal.eval.model.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
- close #135 
- personal page resolver 개선
=> feat ✨  scale team

app/src/api/cursusUser/cursusUser.service.ts, app/src/api/experienceUser/db/experiecneUser.database.aggregate.ts, app/src/api/experienceUser/db/experienceUser.database.schema.ts, app/src/api/experienceUser/experienceUser.module.ts, app/src/api/experienceUser/experienceUser.service.ts, app/src/api/project/db/project.database.schema.ts, app/src/common/db/common.db.aggregation.ts, app/src/page/home/user/home.user.service.ts, app/src/page/leaderboard/exp/leaderboard.exp.module.ts, app/src/page/leaderboard/exp/leaderboard.exp.service.ts, app/src/statDate/StatDate.ts
=> feat ✨  user state

app/src/api/location/location.service.ts, app/src/common/models/common.dateRanaged.model.ts, app/src/common/models/common.rate.model.ts, app/src/page/home/user/home.user.resolver.ts, app/src/page/home/user/home.user.service.ts, app/src/page/home/user/models/home.user.model.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
- personal page logtime 단위 분으로 변경
- Rate type 생성
=> refactor ♻️  types

app/src/api/project/db/project.database.aggregate.ts, app/src/api/project/project.service.ts, app/src/api/team/db/team.database.schema.ts, app/src/api/team/team.module.ts, app/src/api/team/team.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.module.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> feat: :sparkles: user team info 추가

app/package.json, app/src/app.module.ts, app/src/page/landing/landing.module.ts, app/src/page/landing/landing.resolver.ts, app/src/page/landing/landing.service.ts, app/src/page/landing/models/landing.model.ts, app/src/schema.gql
- close #146
project 관련 정보는 #80 완성 후에 제작하겠습니다.
=> feat: :sparkles: landing page 제작

app/src/api/experienceUser/experienceUser.module.ts, app/src/page/evalLog/evalLog.module.ts, app/src/page/home/coalition/home.coalition.module.ts, app/src/page/home/eval/home.eval.module.ts, app/src/page/home/user/home.user.module.ts, app/src/page/landing/landing.module.ts, app/src/page/leaderboard/eval/leaderboard.eval.module.ts, app/src/page/leaderboard/exp/leaderboard.exp.module.ts, app/src/page/leaderboard/level/leaderboard.level.module.ts, app/src/page/leaderboard/score/leaderboard.score.module.ts, app/src/page/myInfo/myInfo.module.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/eval/personal.eval.module.ts, app/src/page/personal/general/personal.general.module.ts
- close #158 
앞선 풀리퀘 먼저 merge 하고 rebase 해야합니다.
=> fix 🐛  dependency

app/src/api/cursusUser/cursusUser.service.ts, app/src/common/db/common.db.aggregation.ts, app/src/statDate/StatDate.ts
=> fix: :bug: bucket 에서 default 값에 대해 적절히 처리되지 않는 오류 수정

app/src/api/cursusUser/cursusUser.service.ts, app/src/api/project/project.service.ts, app/src/api/projectSession/db/projectSession.database.aggregate.ts, app/src/api/projectSession/db/projectSession.database.schema.ts, app/src/api/projectSession/projectSession.module.ts, app/src/api/projectSession/projectSession.service.ts, app/src/api/projectSessionsSkill/db/projectSessionsSkill.database.aggregate.ts, app/src/api/projectSessionsSkill/db/projectSessionsSkill.database.schema.ts, app/src/api/projectsUser/db/projectsUser.database.schema.ts, app/src/api/projectsUser/projectsUser.module.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/api/questsUser/questsUser.service.ts, app/src/api/skill/db/skill.database.aggregate.ts, app/src/api/skill/db/skill.database.schema.ts, app/src/api/team/team.service.ts, app/src/page/home/team/home.team.module.ts, app/src/page/home/team/home.team.resolver.ts, app/src/page/home/team/home.team.service.ts, app/src/page/projectInfo/models/projectInfo.model.ts, app/src/page/projectInfo/projectInfo.module.ts, app/src/page/projectInfo/projectInfo.resolver.ts, app/src/page/projectInfo/projectInfo.service.ts, app/src/schema.gql
- #150 에서 브랜치 이름 변경 후 다시 열었습니다.
- close #80
=> feat ✨ project

app/src/api/cursusUser/cursusUser.cache.service.ts, app/src/api/location/db/location.database.aggregate.ts, app/src/api/location/location.cache.service.ts, app/src/api/location/location.module.ts, app/src/api/location/location.service.ts, app/src/api/project/project.service.ts, app/src/api/projectsUser/db/projectsUser.database.schema.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/team/team.service.ts, app/src/cache/cache.module.ts, app/src/cache/cache.service.ts, app/src/cache/inMemory/cache.inMemory.module.ts, app/src/cache/inMemory/cache.inMemory.service.ts, app/src/common/assertExist.ts, app/src/common/partition.ts, app/src/page/evalLog/evalLog.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.module.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/projectInfo/projectInfo.service.ts, app/src/schema.gql
- close #85 
- close #155 
- close #170
- close #175 
- #154
=> feat ✨  character

app/src/api/team/team.service.ts, app/src/page/home/team/home.team.service.ts
이외 이슈에 적힌 문제들도 처리했습니다
close - #184
=> fix: :bug: rank값 id에서 실제 exam rank로 바꾸기

app/package.json, app/src/api/project/project.service.ts, app/src/api/projectSession/projectSession.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/team/team.service.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/projectInfo/models/projectInfo.model.ts, app/src/page/projectInfo/projectInfo.service.ts, app/src/schema.gql
- close #174 
- close #176 
- close #183 
- close #187
=> fix 🐛  bugs

app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/team/team.service.ts, app/src/page/personal/eval/models/personal.eval.model.ts, app/src/page/personal/eval/personal.eval.module.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/schema.gql
=> feat: ✨ destiny user rank

app/src/api/exam/exam.service.ts, app/src/api/team/team.service.ts, app/src/page/home/team/home.team.service.ts, app/src/page/home/team/models/home.team.model.ts, app/src/schema.gql, app/src/statDate/StatDate.ts
- close #190 
- reflog로 돌렸다가 브랜치가 새로 만들어지면서 #193 이 닫혔습니다 😢
=> fix: 🐛 examresult

app/src/api/location/location.service.ts
=> fix: :bug: logtime service 버그 수정

app/src/app.module.ts, app/src/http-exception.filter.ts, app/src/page/evalLog/evalLog.resolver.ts, app/src/page/home/coalition/home.coalition.resolver.ts, app/src/page/home/eval/home.eval.resolver.ts, app/src/page/home/team/home.team.resolver.ts, app/src/page/home/user/home.user.resolver.ts, app/src/page/landing/landing.resolver.ts, app/src/page/leaderboard/eval/leaderboard.eval.resolver.ts, app/src/page/leaderboard/exp/leaderboard.exp.resolver.ts, app/src/page/leaderboard/level/leaderboard.level.resovler.ts, app/src/page/leaderboard/score/leaderboard.score.resolver.ts, app/src/page/myInfo/myInfo.resolver.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/projectInfo/projectInfo.resolver.ts
- close #200 
---
- env 를 통해 dev, prod 별로 stacktrace 값 바꾸기
=> feat ✨ graphql error

app/src/api/coalition/coalition.service.ts, app/src/api/cursusUser/cursusUser.resolver.ts, app/src/api/cursusUser/cursusUser.service.ts, app/src/api/exam/exam.service.ts, app/src/api/level/level.service.ts, app/src/api/project/dtos/project.dto.ts, app/src/api/project/models/project.preview.ts, app/src/api/project/project.resolver.ts, app/src/api/project/project.service.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/api/questsUser/questsUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/team/team.service.ts, app/src/common/db/common.db.query.ts, app/src/page/evalLog/evalLog.service.ts, app/src/page/home/coalition/models/home.coalition.model.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/eval/models/personal.eval.model.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/models/personal.general.userProfile.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/projectInfo/models/projectInfo.model.ts, app/src/page/projectInfo/projectInfo.service.ts, app/src/pagination/cursor/models/pagination.cursor.model.ts, app/src/pagination/index/models/pagination.index.model.ts, app/src/schema.gql
=> refactor ♻️  search

app/src/api/project/project.service.ts, app/src/api/projectSession/projectSession.service.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/team/team.service.ts, app/src/page/projectInfo/models/projectInfo.model.ts, app/src/page/projectInfo/projectInfo.service.ts, app/src/schema.gql
=> feat: ✨  projectInfo 에 url 추가

app/src/api/cursusUser/db/cursusUser.database.query.ts, app/src/api/experienceUser/experienceUser.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
기존의 레벨 증가 그래프에서 어떤 방식으로 변경할지 회의한 결과대로 변경합니다.
- close #188
=> feat: ✨  기수 전체 평균, 기수 멤버 평균, 유저 평균 레벨 그래프 구현

app/src/api/score/db/score.database.aggregate.ts, app/src/lambda/lambda.service.ts
로직 옮기다 잘못 옮겼던게 있네요.
blackhole 간 사람들에 대한 filter 는 따로 어디에 만들어두면 좋을 것 같긴 합니다.
(아니면 그냥 cursusUserService 를 호출해서 좀 느리게 하는 것도 방법입니다.)
=> fix: 🐛  캐시 수정 중 기존 로직에서 적절히 반영되지 않은 부분 수정

app/src/app.module.ts, app/src/cache/decrators/onReturn/cache.decorator.onReturn.module.ts, app/src/cache/decrators/onReturn/cache.decorator.onReturn.register.ts, app/src/cache/decrators/onReturn/cache.decorator.onReturn.symbol.ts, app/src/cache/shallowStore/cache.shallowStore.ts, app/src/lambda/lambda.module.ts, app/src/lambda/lambda.register.ts, app/src/lambda/lambda.service.ts, app/src/page/home/coalition/home.coalition.service.ts, app/src/page/home/eval/home.eval.service.ts, app/src/page/home/team/home.team.service.ts, app/src/page/home/user/home.user.service.ts, app/src/page/landing/landing.service.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/projectInfo/projectInfo.service.ts
=> feat: ✨   cache

app/src/api/cursusUser/cursusUser.cache.service.ts, app/src/api/experienceUser/experienceUser.cache.service.ts, app/src/api/location/location.cache.service.ts, app/src/api/scaleTeam/scaleTeam.cache.service.ts, app/src/api/score/score.cache.service.ts, app/src/cache/cache.util.service.ts, app/src/page/leaderboard/leaderboard.type.ts, app/src/page/leaderboard/score/leaderboard.score.service.ts, app/src/page/leaderboard/util/leaderboard.util.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> feat: ✨  character usercount

app/src/api/exam/exam.service.ts, app/src/cache/shallowStore/cache.shallowStore.ts, app/src/page/personal/general/character/models/personal.general.character.model.ts, app/src/page/personal/general/character/persoanl.general.character.module.ts, app/src/page/personal/general/character/personal.general.characer.table.ts, app/src/page/personal/general/character/personal.general.character.pokemon.ts, app/src/page/personal/general/character/personal.general.character.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.module.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> refactor ♻️ character

app/src/page/personal/personal.module.ts, app/src/page/personal/versus/models/personal.versus.model.ts, app/src/page/personal/versus/personal.versus.module.ts, app/src/page/personal/versus/personal.versus.resolver.ts, app/src/page/personal/versus/personal.versus.service.ts, app/src/schema.gql
=> feat ✨  versus

app/.eslintrc.js, app/src/app.module.ts, app/src/cache/shallowStore/cache.shallowStore.ts, app/src/page/home/eval/home.eval.service.ts, app/src/page/landing/landing.service.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/general/character/personal.general.character.service.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/projectInfo/projectInfo.service.ts
=> refactor: ♻️  캐시 할 필요 없던 부분 private 함수로 변경, cache max, ttl 설정 변경

app/src/api/cursusUser/cursusUser.service.ts, app/src/api/cursusUser/db/cursusUser.database.query.ts, app/src/api/experienceUser/experienceUser.service.ts, app/src/api/location/location.service.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/app.module.ts, app/src/cache/cache.util.service.ts, app/src/cache/decrators/onReturn/cache.decorator.onReturn.symbol.ts, app/src/cache/shallowStore/cache.shallowStore.ts, app/src/dateRange/dateRange.service.ts, app/src/lambda/lambda.register.ts, app/src/lambda/lambda.service.ts, app/src/login/login.service.ts, app/src/page/home/coalition/home.coalition.service.ts, app/src/page/home/team/home.team.service.ts, app/src/page/home/user/home.user.service.ts, app/src/page/landing/landing.service.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/general/character/personal.general.character.service.ts, app/src/page/personal/general/personal.general.service.ts, app/src/statDate/StatDate.ts
=> refactor ♻️  stat date

app/src/api/coalition/coalition.service.ts, app/src/api/coalition/models/coalition.model.ts, app/src/api/cursusUser/cursusUser.module.ts, app/src/api/cursusUser/cursusUser.service.ts, app/src/api/cursusUser/db/cursusUser.database.aggregate.ts, app/src/api/score/db/score.database.aggregate.ts, app/src/api/score/score.service.ts, app/src/app.module.ts, app/src/cache/cache.util.service.ts, app/src/common/db/common.db.query.ts, app/src/config/api.ts, app/src/config/cdn.ts, app/src/lambda/lambda.service.ts, app/src/page/home/coalition/home.coalition.service.ts, app/src/page/leaderboard/score/leaderboard.score.service.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/general/character/personal.general.character.pokemon.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> refactor ♻️  coalition

app/src/page/personal/eval/personal.eval.service.ts
- #256 에서 잘못 수정한 부분을 추가로 작성하였습니다.
=> fix: :bug: throw를 추가하지 않아 생기던 컴파일 오류 수정

app/src/api/cursusUser/cursusUser.cache.service.ts, app/src/api/location/location.cache.service.ts, app/src/api/scaleTeam/scaleTeam.cache.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/cache/cache.util.service.ts, app/src/lambda/lambda.service.ts, app/src/page/leaderboard/eval/leaderboard.eval.resolver.ts, app/src/page/leaderboard/eval/leaderboard.eval.service.ts, app/src/page/leaderboard/exp/leaderboard.exp.resolver.ts, app/src/page/leaderboard/exp/leaderboard.exp.service.ts, app/src/page/leaderboard/level/leaderboard.level.resovler.ts, app/src/page/leaderboard/level/leaderboard.level.service.ts, app/src/page/leaderboard/score/leaderboard.score.resolver.ts, app/src/page/leaderboard/score/leaderboard.score.service.ts, app/src/page/leaderboard/util/leaderboard.util.service.ts, app/src/page/personal/versus/models/personal.versus.model.ts, app/src/page/personal/versus/personal.versus.service.ts, app/src/schema.gql
- close #242
- close #250 
- close #251 
세 이슈가 연관된 부분이 커서, 같이 진행했습니다.
=> refactor ✨ ♻️ 🐛  ranking cache

app/src/api/cursusUser/cursusUser.service.ts, app/src/api/cursusUser/db/cursusUser.database.aggregate.ts, app/src/api/cursusUser/db/cursusUser.database.schema.ts, app/src/api/experienceUser/experienceUser.service.ts, app/src/api/location/db/location.database.schema.ts, app/src/api/projectsUser/db/projectsUser.database.schema.ts, app/src/api/questsUser/db/questsUser.database.schema.ts, app/src/api/scaleTeam/db/scaleTeam.database.schema.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/score/score.service.ts, app/src/api/team/db/team.database.schema.ts, app/src/api/team/team.service.ts, app/src/api/user/db/user.database.aggregate.ts, app/src/api/user/db/user.database.schema.ts, app/src/api/user/user.module.ts, app/src/api/user/user.service.ts, app/src/cache/cache.util.service.ts, app/src/lambda/lambda.service.ts, app/src/page/evalLog/evalLog.module.ts, app/src/page/evalLog/evalLog.service.ts, app/src/page/personal/eval/personal.eval.service.ts
=> feat ✨  user api

app/src/api/cursusUser/cursusUser.resolver.ts, app/src/api/cursusUser/cursusUser.service.ts, app/src/api/project/project.resolver.ts, app/src/api/project/project.service.ts, app/src/app.module.ts, app/src/config/api.ts, app/src/page/search/dtos/search.dto.getSearchResult.ts, app/src/page/search/models/search.model.ts, app/src/page/search/search.module.ts, app/src/page/search/search.resovler.ts, app/src/page/search/search.service.ts, app/src/schema.gql
=> refactor: :recycle: 기존 검색 로직을 search module 로 분리

app/src/api/project/db/project.database.aggregate.ts, app/src/api/project/db/project.database.schema.ts, app/src/api/project/project.service.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/team/team.service.ts, app/src/config/api.ts, app/src/page/projectInfo/projectInfo.service.ts
원본 project collection 을 백업하고, 앞으로는 circle field 를 임의로 추가한 새 project collection 을 통해 가져옵니다.
=> refactor: ♻️  project circle 을 db 에서 가져오도록 변경

app/src/api/cursusUser/cursusUser.resolver.ts, app/src/api/cursusUser/cursusUser.service.ts, app/src/api/exam/exam.service.ts, app/src/api/experienceUser/experienceUser.service.ts, app/src/api/level/level.service.ts, app/src/api/project/project.resolver.ts, app/src/api/project/project.service.ts, app/src/api/projectsUser/projectsUser.service.ts, app/src/api/questsUser/questsUser.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/api/user/user.service.ts, app/src/auth/statAuthGuard.ts, app/src/auth/token/token.service.ts, app/src/common/db/common.db.query.ts, app/src/login/account/account.service.ts, app/src/login/login.service.ts, app/src/page/evalLog/evalLog.service.ts, app/src/page/home/team/home.team.service.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/util/personal.util.service.ts, app/src/page/search/search.resovler.ts
=> refactor ♻️ check query

app/src/api/project/db/project.database.aggregate.ts, app/src/api/scaleTeam/db/scaleTeam.database.schema.ts, app/src/api/team/db/team.database.schema.ts, app/src/api/team/team.service.ts, app/src/app.module.ts, app/src/page/evalLog/models/evalLog.model.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/page/teamInfo/models/teamInfo.base.model.ts, app/src/page/teamInfo/models/teamInfo.model.ts, app/src/page/teamInfo/models/teamInfo.status.model.ts, app/src/page/teamInfo/teamInfo.module.ts, app/src/page/teamInfo/teamInfo.resolver.ts, app/src/page/teamInfo/teamInfo.service.ts, app/src/schema.gql
=> feat: :sparkles: team page api

app/src/api/location/location.service.ts, app/src/api/team/team.service.ts, app/src/page/home/eval/home.eval.resolver.ts, app/src/page/home/eval/home.eval.service.ts, app/src/page/home/eval/models/home.eval.model.ts, app/src/page/home/team/dtos/home.team.dto.recentExamResultArgs.ts, app/src/page/home/team/home.team.resolver.ts, app/src/page/home/team/home.team.service.ts, app/src/page/home/team/models/home.team.model.ts, app/src/page/home/user/home.user.resolver.ts, app/src/page/home/user/home.user.service.ts, app/src/page/home/user/models/home.user.model.ts, app/src/page/personal/eval/models/personal.eval.model.ts, app/src/page/personal/eval/personal.eval.resolver.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> feat: :sparkles: #270 에 따라 record 반환하는 endpoint 추가

app/src/cache/cache.util.ranking.service.ts, app/src/dateRange/dateRange.service.ts, app/src/dateRange/dtos/dateRange.dto.ts, app/src/page/home/eval/home.eval.service.ts, app/src/page/home/team/home.team.service.ts, app/src/page/home/user/home.user.service.ts, app/src/page/personal/eval/personal.eval.service.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> fix 🐛  record zero value

app/src/api/team/team.service.ts, app/src/page/teamInfo/models/teamInfo.model.ts, app/src/schema.gql
=> feat: :sparkles: team info 에 user 추가 정보, finalMark 추가

app/src/api/team/team.service.ts, app/src/page/teamInfo/models/teamInfo.model.ts, app/src/schema.gql
=> feat: :sparkles: team info 에서 last event time 을 추가

app/src/api/location/location.service.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/projectInfo/models/projectInfo.model.ts, app/src/schema.gql
=> fix: :bug: project info 에서 circle 의 gql schema 가 nullable 하지 않던 문제 수정

app/src/api/score/score.service.ts, app/src/lambda/lambda.service.ts, app/src/page/home/coalition/home.coalition.service.ts
=> refactor: ♻️ coalition score record 가 이번 달 점수를 포함해서 반환하도록 변경 

app/src/cache/decrators/onReturn/cache.decorator.onReturn.register.ts, app/src/lambda/lambda.service.ts, app/src/page/myInfo/models/myInfo.model.ts, app/src/page/myInfo/myInfo.module.ts, app/src/page/myInfo/myInfo.resolver.ts, app/src/page/myInfo/myInfo.service.ts, app/src/page/personal/eval/models/personal.eval.model.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/schema.gql
=> fix 🐛  dayone

.github/workflows/cicd.yml
- github secrets 등록했습니다. 
- https://github.com/appleboy/ssh-action#input-variables
- #272
-  close #74
=> build: :recycle: github action 수정

app/src/main.ts
- close 302
이 풀리퀘를 통해 깃헙 액션도 테스트 ...
=> fix: :bug: cors 누락된 설정 추가

.github/workflows/cicd.yml
=> fix: :bug: syntax error 수정

.github/workflows/cicd.yml
=> fix: :bug: 절대경로로 변경, 디버깅용 echo 추가

app/src/page/home/team/home.team.service.ts
=> fix: :bug: teamCLoseRecords 에서 시험 제외

app/src/api/scaleTeam/scaleTeam.cache.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/lambda/lambda.service.ts, app/src/page/leaderboard/comment/leaderboard.comment.module.ts, app/src/page/leaderboard/comment/leaderboard.comment.resolver.ts, app/src/page/leaderboard/comment/leaderboard.comment.service.ts, app/src/page/leaderboard/comment/models/leaderboard.comment.model.ts, app/src/page/leaderboard/eval/models/leaderboard.eval.model.ts, app/src/page/leaderboard/exp/leaderboard.exp.service.ts, app/src/page/leaderboard/exp/models/leaderboard.exp.model.ts, app/src/page/leaderboard/leaderboard.module.ts, app/src/page/leaderboard/level/leaderboard.level.resovler.ts, app/src/page/leaderboard/level/models/leaderboard.level.model.ts, app/src/schema.gql
lookup pipeline 내부에서 ` 를 사용하기 위해 동적 피드인 expr을 사용했습니다.
'comment' 와 'corrector' 를 페어로 지정할까 고민하다가... 일단 따로 받도록 두었습니다.
눈으로 보고 이해했을 때랑 직접 사용할 때가 또 달랐는데... 혹시 잘못 이해하고 사용한 것 같은 부분이 있으면 알려주세요
- close #319
=> feat: :sparkles: commentRanking 추가

app/src/api/score/score.cache.service.ts, app/src/api/score/score.service.ts, app/src/page/home/coalition/home.coalition.resolver.ts, app/src/page/home/coalition/home.coalition.service.ts, app/src/schema.gql
=> feat: :sparkles: winCountPerCoalition 추가

app/src/api/scaleTeam/scaleTeam.service.ts, app/src/page/leaderboard/score/leaderboard.score.resolver.ts, app/src/page/leaderboard/score/models/leaderboard.score.model.ts, app/src/schema.gql
size 와 달리 strLenCP 는 0 이 아닌 null 을 반환해 ifNull 을 추가하였습니다.
이외 한국어로 통일하기로 한 주석도 하나 수정했습니다.
- close #325
=> fix: :bug: 0 점일 때 null 로 반환되던 로직 수정

app/src/api/score/score.service.ts
=> refactor: :recycle: coalition 순서 정렬해 반환하도록 변경

app/src/api/project/project.service.ts, app/src/app.module.ts, app/src/common/models/common.project.model.ts, app/src/page/calculator/calculator.module.ts, app/src/page/calculator/calculator.resolver.ts, app/src/page/calculator/calculator.service.ts, app/src/page/calculator/models/calculator.model.ts, app/src/schema.gql
=> feat: :sparkles: blackhole calculator 추가

app/src/api/score/score.service.ts, app/src/page/home/coalition/home.coalition.service.ts
- lookup 했을 때 0개가 나오는 경우, coalition 자체가 반환이 안되기 때문에 애초에 aggregate 를 coalition 기준으로 하도록 변경
-  특정 날짜에 대해 없는 경우 records 의 개수가 date 범위와 맞지 않기 때문에 이를 0 으로 채워서 반환하도록 수정
- close #332
=> fix: :bug: scoreRecordsPerCoalition 에서 coalition 이 얻은 점수가 없는 경우에 대한 처리

app/src/api/score/score.service.ts
고민하다가 조금 돌아왔는데 생각했던 것에 대해 이슈에 적어뒀습니다.
도움 요청 목적의 풀리퀘이기도 해서... 다른 좋은 방법이 있다면 알려주세요 💭 
- close #333
=> fix: :bug: 코알리숑이 없는 유저의 코알리숑 순위에서 throw 를 0 반환으로 수정

app/src/api/score/score.service.ts, app/src/config/database.ts, app/src/database/mongoose/database.mongoose.module.ts
=> fix: 🐛  dev 변경 사항 중 #343 과 연관된 부분 추가 수정

app/src/cache/cache.util.ranking.service.ts
이후 nullable 인자 받을 때를 위한 규칙을 세워서 정리하는 일이 필요할 것으로 보입니다.
- close #351
=> fix 🐛  promo null value

app/package.json, app/src/api/team/team.service.ts, app/src/api/team/test/team.test.spec.ts
test 도 같이 추가 했습니다.
- close #352
=> fix: 🐛  destinyUserRanking 에서 잘못 작성된 aggregation 수정

app/src/api/scaleTeam/scaleTeam.cache.service.ts, app/src/api/scaleTeam/scaleTeam.service.ts, app/src/lambda/lambda.service.ts, app/src/page/leaderboard/comment/leaderboard.comment.resolver.ts, app/src/page/leaderboard/comment/leaderboard.comment.service.ts, app/src/page/leaderboard/comment/models/leaderboard.comment.model.ts, app/src/schema.gql
=> feat ✨  comment ranking by date

Dockerfile
=> fix 🐛  dockerfile

app/src/login/login.service.ts
=> fix 🐛  handle google login fail

app/src/lib/regexFind/regexFind.service.ts
=> fix 🐛  search limit error

app/src/lambda/lambda.controller.ts, app/src/lambda/lambda.service.ts
기존 방식으로 할 경우 response time alarm 에 걸려 수정하기로 했습니다.
- close #365
=> refactor: :recycle: lambda update response 를 즉시 보내도록 변경

app/src/page/myInfo/models/myInfo.model.ts, app/src/page/myInfo/myInfo.module.ts, app/src/page/myInfo/myInfo.resolver.ts, app/src/page/myInfo/myInfo.service.ts, app/src/schema.gql
기존에 묶지 않고 제공하는 field 들로 인해 type 의 가독성이 떨어진다고 생각하여 recentActivity 를 추가했습니다.
- close #367
=> feat: :sparkles: getMyInfo 에 beginAt, level, recentActivity 추가

app/src/api/coalitionsUser/coalitionsUserModule.ts, app/src/api/coalitionsUser/coalitionsUserService.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.module.ts, app/src/page/personal/general/personal.general.service.ts, app/src/schema.gql
=> fix: :bug: personal general 의 score info 에서 공동 순위에 대한 처리가 없던 문제

app/src/page/evalLog/dtos/evalLog.dto.getEvalLog.ts, app/src/page/evalLog/evalLog.service.ts, app/src/schema.gql
=> feat: :sparkles: getEvalLogArgs 에 imperfectOnly 추가

app/package.json, app/pnpm-lock.yaml, app/src/api/projectSession/projectSession.service.ts, app/src/page/myInfo/models/myInfo.model.ts, app/src/schema.gql
=> release 🚀  v0.9.0

app/src/cache/cache.util.service.ts, app/src/dailyActivity/dailyActivity.dto.ts, app/src/dailyActivity/dailyActivity.service.spec.ts, app/src/dailyActivity/dailyActivity.service.ts, app/src/dailyActivity/db/dailyActivity.database.dao.ts, app/src/page/personal/general/models/personal.general.dailyActivity.model.ts, app/src/page/personal/general/models/personal.general.model.ts, app/src/page/personal/general/personal.general.resolver.ts, app/src/schema.gql
=> feat: :sparkles: daily activity detail records 추가

app/src/api/project/db/project.database.aggregate.ts, app/src/dailyActivity/db/dailyActivity.database.dao.ts
- close #409
기본에 netwhat 관련된 부분을 처리하던 방법과 동일하게 만들었습니다.
그리고 주석에
// todo: project collection 수정하고 s 삭제
라고 적혀있던데, 어떤 작업을 하려던건지 궁금합니다.
=> fix: :bug: netwhat 이름을 찾도록 conditionalProjectName 추가

app/src/api/cursusUser/cursusUser.cache.service.ts, app/src/follow/db/follow.database.schema.ts, app/src/follow/dto/follow.dto.ts, app/src/follow/follow.cache.service.ts, app/src/follow/follow.module.ts, app/src/follow/follow.resolver.ts, app/src/follow/follow.service.ts, app/src/follow/model/follow.model.ts, app/src/lambda/lambda.module.ts, app/src/lambda/lambda.service.ts, app/src/schema.gql
- close #413
(un)follow 실패시 cache 동작 못하게 막기
-> 예외처리
cache실패시 db롤백
-> 트랜젝션 (안함)
현재 db실패시 cache안하게만 해줌
사용하는 db temp_ 는 마지막에 지우겠습니당
=> feat ✨ follow cache

app/src/activeUserCount/activeUserCount.dto.ts, app/src/activeUserCount/activeUserCount.module.ts, app/src/activeUserCount/activeUserCount.service.ts, app/src/activeUserCount/db/activeUserCount.db.dao.ts, app/src/activeUserCount/db/activeUserCount.db.dto.ts, app/src/activeUserCount/db/activeUserCount.db.schema.ts, app/src/dailyActivity/dailyActivity.service.ts, app/src/page/home/user/home.user.module.ts, app/src/page/home/user/home.user.resolver.ts, app/src/page/home/user/home.user.service.ts, app/src/page/home/user/models/home.user.model.ts, app/src/schema.gql
실제로 활동중인 유저 수를 db collection 으로 따로 생성 했습니다.
scale team 참여자, logtime 보유자 기준 집계 입니다.
기존 작업중인 내역 때문에 main 에 바로 merge 합니다.
=> monthly active user count 추가
